.TH NovusCLI 8 "01 Jan 2019" "2.1" "NovusCLI man page"
.SH NAME
NovusCLI \- A Command Line frontend for APT.
.SH SYNOPSIS
nvs [OPTION] [PACKAGE]

nvs search [QUERY]

nvs install [PACKAGE]

nvs remove [PACKAGE] \- Removes a package

nvs autoremove \- Removes unnecessary

nvs upgrade (PACKAGES) \- Upgrades system or set of packages

nvs clean \- Cleans the cache

nvs help \- Shows a help page

nvs about \- View package/license information
.SH DESCRIPTION
NovusCLI is a frontend via command line for our port of APT to macOS.

.SH USAGE
NovusCLI was made for the command line, but a GUI for it it's coming later this year!
.SH BUGS
Report bugs here at https://github.com/DiegoMagdaIeno/NovusCommandLineEdition/issues. You will need a github account to do so. If you do not, please email diegomagdaleno@protonmail.com
.SH AUTHOR
Emil Engler (me@emilengler.com) (Original author of Sysget)
